### PR TITLE
Static Code Analysis: get rid of is_null() and alias functions, use mt_* random api, 

### PR DESCRIPTION
**Pull request by kalessil**
UTs passed
Non-functional changes

### CODE REVIEW

**Comment by kalessil** [comment]
`The command "php composer.phar install --prefer-source" failed and exited with 1 during .`

Travis fails, so I'll try to make one more commit later - hopefully travis will not fail then.

**Comment by kalessil** [comment]
@willdurand : is propelorm/Propel still maintained or all new PRs will remain unmerged?

**Comment by marcj** [comment]
Those pull-requests remain unmerged since we're merging only security fixes and critical bug fixes. Why? Because it's too much work and there's currently no volunteer who can spend so much time maintaining version 1. This library is too widely used to just merge everything without keeping a really close eye on each line of code.

**Comment by kalessil** [comment]
@marcj : thank you for your answer. What needs to be done to become such a volunteer?

**Comment by harikt** [comment]
@kalessil using `sudo false` on travis.yml . It will get passed I believe. Similar PR https://github.com/psecio/gatekeeper/pull/30

**Comment by kalessil** [comment]
Thank you @harikt , will try this.

**Comment by harikt** [comment]
@kalessil cool . Let me know how things goes then.

**Comment by marcj** [comment]
> @marcj : thank you for your answer. What needs to be done to become such a volunteer?

@kalessil, just start contributing: review pull-requests, fix bugs, help people. If a given threshold is reached you're automatically that contributor. In the open-source world is no written contract necessary to become a volunteer/contributor.

**Pull request closed without merging**
